insert into authors (author_name) values ('Drucie Goodbourn');
insert into authors (author_name) values ('Marcia Aggiss');
insert into authors (author_name) values ('Giovanni Bigg');
insert into authors (author_name) values ('Duffie Eynon');
insert into authors (author_name) values ('Anselma McKennan');
insert into authors (author_name) values ('Gert Kira');
insert into authors (author_name) values ('Clerc Djakovic');
insert into authors (author_name) values ('Stacee Elsy');
insert into authors (author_name) values ('Dorotea Bonhill');
insert into authors (author_name) values ('Minni Bunney');
insert into authors (author_name) values ('Berty Gandley');
insert into authors (author_name) values ('Raynard Tesdale');
insert into authors (author_name) values ('Joanna Hutfield');
insert into authors (author_name) values ('Dannie Glidder');
insert into authors (author_name) values ('Timmie Adshede');
insert into authors (author_name) values ('Fernando Neads');
insert into authors (author_name) values ('Teddy Guilliland');
insert into authors (author_name) values ('Paloma Grebert');
insert into authors (author_name) values ('Kristos Usher');
insert into authors (author_name) values ('Darcey Rohmer');
insert into authors (author_name) values ('Cristie Isacsson');
insert into authors (author_name) values ('Lindsay Coutthart');
insert into authors (author_name) values ('Helyn Schneidar');
insert into authors (author_name) values ('Bette-ann Askem');
insert into authors (author_name) values ('Dom Robuchon');
insert into books (author_id, title, priceOld, price) select author_id, 'exploit real-time e-commerce', '$203.23', '$43.37' from authors where author_name = 'Drucie Goodbourn';
insert into books (author_id, title, priceOld, price) select author_id, 'utilize real-time interfaces', '$260.31', '$35.96' from authors where author_name = 'Marcia Aggiss';
insert into books (author_id, title, priceOld, price) select author_id, 'extend strategic e-services', '$272.00', '$151.04' from authors where author_name = 'Giovanni Bigg';
insert into books (author_id, title, priceOld, price) select author_id, 'iterate integrated solutions', '$271.58', '$141.40' from authors where author_name = 'Duffie Eynon';
insert into books (author_id, title, priceOld, price) select author_id, 'cultivate magnetic e-commerce', '$278.43', '$54.44' from authors where author_name = 'Anselma McKennan';
insert into books (author_id, title, priceOld, price) select author_id, 'architect vertical ROI', '$282.54', '$102.61' from authors where author_name = 'Gert Kira';
insert into books (author_id, title, priceOld, price) select author_id, 'disintermediate extensible architectures', '$295.38', '$181.27' from authors where author_name = 'Clerc Djakovic';
insert into books (author_id, title, priceOld, price) select author_id, 'extend leading-edge methodologies', '$283.08', '$97.96' from authors where author_name = 'Stacee Elsy';
insert into books (author_id, title, priceOld, price) select author_id, 'integrate one-to-one systems', '$258.51', '$52.25' from authors where author_name = 'Dorotea Bonhill';
insert into books (author_id, title, priceOld, price) select author_id, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69' from authors where author_name = 'Minni Bunney';
insert into books (author_id, title, priceOld, price) select author_id, 'enhance innovative e-services', '$256.54', '$160.98' from authors where author_name = 'Berty Gandley';
insert into books (author_id, title, priceOld, price) select author_id, 'maximize 24/365 e-tailers', '$262.07', '$34.06' from authors where author_name = 'Raynard Tesdale';
insert into books (author_id, title, priceOld, price) select author_id, 'scale integrated architectures', '$257.66', '$32.97' from authors where author_name = 'Joanna Hutfield';
insert into books (author_id, title, priceOld, price) select author_id, 'e-enable frictionless web services', '$288.19', '$90.52' from authors where author_name = 'Dannie Glidder';
insert into books (author_id, title, priceOld, price) select author_id, 'strategize B2B channels', '$232.27', '$44.83' from authors where author_name = 'Timmie Adshede';
insert into books (author_id, title, priceOld, price) select author_id, 'syndicate compelling deliverables', '$287.45', '$101.89' from authors where author_name = 'Fernando Neads';
insert into books (author_id, title, priceOld, price) select author_id, 'utilize bleeding-edge users', '$281.37', '$146.21' from authors where author_name = 'Teddy Guilliland';
insert into books (author_id, title, priceOld, price) select author_id, 'cultivate 24/365 networks', '$270.99', '$184.76' from authors where author_name = 'Paloma Grebert';
insert into books (author_id, title, priceOld, price) select author_id, 'embrace plug-and-play platforms', '$278.36', '$77.71' from authors where author_name = 'Kristos Usher';
insert into books (author_id, title, priceOld, price) select author_id, 'target innovative paradigms', '$298.94', '$130.01' from authors where author_name = 'Darcey Rohmer';
insert into books (author_id, title, priceOld, price) select author_id, 'generate open-source e-business', '$276.57', '$113.25' from authors where author_name = 'Cristie Isacsson';
insert into books (author_id, title, priceOld, price) select author_id, 'implement user-centric e-markets', '$254.70', '$115.31' from authors where author_name = 'Lindsay Coutthart';
insert into books (author_id, title, priceOld, price) select author_id, 'utilize magnetic supply-chains', '$279.70', '$77.86' from authors where author_name = 'Helyn Schneidar';
insert into books (author_id, title, priceOld, price) select author_id, 'e-enable dot-com supply-chains', '$297.83', '$110.15' from authors where author_name = 'Bette-ann Askem';
insert into books (author_id, title, priceOld, price) select author_id, 'facilitate efficient eyeballs', '$232.30', '$131.48' from authors where author_name = 'Dom Robuchon';