insert into author (id, name, slug) values (1, 'Drucie Goodbourn', '');
insert into author (id, name, slug) values (2, 'Marcia Aggiss', '');
insert into author (id, name, slug) values (3, 'Giovanni Bigg', '');
insert into author (id, name, slug) values (4, 'Duffie Eynon', '');
insert into author (id, name, slug) values (5, 'Anselma McKennan', '');
insert into author (id, name, slug) values (6, 'Gert Kira', '');
insert into author (id, name, slug) values (7, 'Clerc Djakovic', '');
insert into author (id, name, slug) values (8, 'Stacee Elsy', '');
insert into author (id, name, slug) values (9, 'Dorotea Bonhill', '');
insert into author (id, name, slug) values (10, 'Minni Bunney', '');
insert into author (id, name, slug) values (11, 'Berty Gandley', '');
insert into author (id, name, slug) values (12, 'Raynard Tesdale', '');
insert into author (id, name, slug) values (13, 'Joanna Hutfield', '');
insert into author (id, name, slug) values (14, 'Dannie Glidder', '');
insert into author (id, name, slug) values (15, 'Timmie Adshede', '');
insert into author (id, name, slug) values (16, 'Fernando Neads', '');
insert into author (id, name, slug) values (17, 'Teddy Guilliland', '');
insert into author (id, name, slug) values (18, 'Paloma Grebert', '');
insert into author (id, name, slug) values (19, 'Timmie Usher', '');
insert into author (id, name, slug) values (20, 'Darcey Rohmer', '');
insert into author (id, name, slug) values (21, 'Cristie Isacsson', '');
insert into author (id, name, slug) values (22, 'Lindsay Coutthart', '');
insert into author (id, name, slug) values (23, 'Helyn Schneidar', '');
insert into author (id, name, slug) values (24, 'Bette-ann Askem', '');
insert into author (id, name, slug) values (25, 'Dom Robuchon', '');
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'exploit real-time e-commerce', '203', '15', '', '', '1', '2017-03-14' from author where name = 'Drucie Goodbourn';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'utilize real-time interfaces', '260', '10', '', '', '1', '2017-03-14' from author where name = 'Marcia Aggiss';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'extend strategic e-services', '272', '0', '', '', '1', '2017-03-14' from author where name = 'Giovanni Bigg';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'iterate integrated solutions', '278', '2', '', '', '1', '2017-03-14' from author where name = 'Duffie Eynon';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'cultivate magnetic e-commerce', '278', '0', '', '', '1', '2017-03-14' from author where name = 'Anselma McKennan';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'architect vertical ROI', '282', '50', '', '', '1', '2017-03-14' from author where name = 'Gert Kira';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'disintermediate extensible architectures', '295', '90', '', '', '1', '2017-03-14' from author where name = 'Clerc Djakovic';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'extend leading-edge methodologies', '283', '0', '', '', '1', '2017-03-14' from author where name = 'Stacee Elsy';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'revolutionize 24/7 infrastructures', '260', '0', '', '', '1', '2017-03-14' from author where name = 'Minni Bunney';
insert into book (author_id, title, price, discount, image, slug, is_bestseller, pub_date) select id, 'integrate one-to-one systems', '258', '0', '', '', '1', '2017-03-14' from author where name = 'Dorotea Bonhill';