insert into author (id, first_name, last_name) values (1, 'Drucie', 'Goodbourn');
insert into author (id, first_name, last_name) values (2, 'Marcia', 'Aggiss');
insert into author (id, first_name, last_name) values (3, 'Giovanni', 'Bigg');
insert into author (id, first_name, last_name) values (4, 'Duffie', 'Eynon');
insert into author (id, first_name, last_name) values (5, 'Anselma', 'McKennan');
insert into author (id, first_name, last_name) values (6, 'Gert', 'Kira');
insert into author (id, first_name, last_name) values (7, 'Clerc', 'Djakovic');
insert into author (id, first_name, last_name) values (8, 'Stacee', 'Elsy');
insert into author (id, first_name, last_name) values (9, 'Dorotea', 'Bonhill');
insert into author (id, first_name, last_name) values (10, 'Minni', 'Bunney');
insert into author (id, first_name, last_name) values (11, 'Berty', 'Gandley');
insert into author (id, first_name, last_name) values (12, 'Raynard', 'Tesdale');
insert into author (id, first_name, last_name) values (13, 'Joanna', 'Hutfield');
insert into author (id, first_name, last_name) values (14, 'Dannie', 'Glidder');
insert into author (id, first_name, last_name) values (15, 'Timmie', 'Adshede');
insert into author (id, first_name, last_name) values (16, 'Fernando', 'Neads');
insert into author (id, first_name, last_name) values (17, 'Teddy', 'Guilliland');
insert into author (id, first_name, last_name) values (18, 'Paloma', 'Grebert');
insert into author (id, first_name, last_name) values (19, 'Timmie', 'Usher');
insert into author (id, first_name, last_name) values (20, 'Darcey', 'Rohmer');
insert into author (id, first_name, last_name) values (21, 'Cristie', 'Isacsson');
insert into author (id, first_name, last_name) values (22, 'Lindsay', 'Coutthart');
insert into author (id, first_name, last_name) values (23, 'Helyn', 'Schneidar');
insert into author (id, first_name, last_name) values (24, 'Bette-ann', 'Askem');
insert into author (id, first_name, last_name) values (25, 'Dom', 'Robuchon');
insert into book (author_id, title, price_old, price) select id, 'exploit real-time e-commerce', '$203.23', '$43.37' from author where last_name = 'Goodbourn';
insert into book (author_id, title, price_old, price) select id, 'utilize real-time interfaces', '$260.31', '$35.96' from author where last_name = 'Aggiss';
insert into book (author_id, title, price_old, price) select id, 'extend strategic e-services', '$272.00', '$151.04' from author where last_name = 'Bigg';
insert into book (author_id, title, price_old, price) select id, 'iterate integrated solutions', '$271.58', '$141.40' from author where last_name = 'Eynon';
insert into book (author_id, title, price_old, price) select id, 'cultivate magnetic e-commerce', '$278.43', '$54.44' from author where last_name = 'McKennan';
insert into book (author_id, title, price_old, price) select id, 'architect vertical ROI', '$282.54', '$102.61' from author where last_name = 'Kira';
insert into book (author_id, title, price_old, price) select id, 'disintermediate extensible architectures', '$295.38', '$181.27' from author where last_name = 'Djakovic';
insert into book (author_id, title, price_old, price) select id, 'extend leading-edge methodologies', '$283.08', '$97.96' from author where last_name = 'Elsy';
insert into book (author_id, title, price_old, price) select id, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69' from author where last_name = 'Minni Bunney';
insert into book (author_id, title, price_old, price) select id, 'integrate one-to-one systems', '$258.51', '$52.25' from author where last_name = 'Bonhill';
insert into book (author_id, title, price_old, price) select id, 'enhance innovative e-services', '$256.54', '$160.98' from author where last_name = 'Gandley';
insert into book (author_id, title, price_old, price) select id, 'maximize 24/365 e-tailers', '$262.07', '$34.06' from author where last_name = 'Tesdale';
insert into book (author_id, title, price_old, price) select id, 'scale integrated architectures', '$257.66', '$32.97' from author where last_name = 'Hutfield';
insert into book (author_id, title, price_old, price) select id, 'e-enable frictionless web services', '$288.19', '$90.52' from author where last_name = 'Glidder';
insert into book (author_id, title, price_old, price) select id, 'strategize B2B channels', '$232.27', '$44.83' from author where last_name = 'Adshede';
insert into book (author_id, title, price_old, price) select id, 'syndicate compelling deliverables', '$287.45', '$.89' from author where last_name = 'Neads';
insert into book (author_id, title, price_old, price) select id, 'utilize bleeding-edge users', '$281.37', '$146.21' from author where last_name = 'Guilliland';
insert into book (author_id, title, price_old, price) select id, 'cultivate 24/365 networks', '$270.99', '$184.76' from author where last_name = 'Grebert';
insert into book (author_id, title, price_old, price) select id, 'embrace plug-and-play platforms', '$278.36', '$77.71' from author where last_name = 'Usher';
insert into book (author_id, title, price_old, price) select id, 'target innovative paradigms', '$298.94', '$130.01' from author where last_name = 'Rohmer';
insert into book (author_id, title, price_old, price) select id, 'generate open-source e-business', '$276.57', '$113.25' from author where last_name = 'Isacsson';
insert into book (author_id, title, price_old, price) select id, 'implement user-centric e-markets', '$254.70', '$115.31' from author where last_name = 'Coutthart';
insert into book (author_id, title, price_old, price) select id, 'utilize magnetic supply-chains', '$279.70', '$77.86' from author where last_name = 'Schneidar';
insert into book (author_id, title, price_old, price) select id, 'e-enable dot-com supply-chains', '$297.83', '$110.15' from author where last_name = 'Askem';
insert into book (author_id, title, price_old, price) select id, 'facilitate efficient eyeballs', '$232.30', '$131.48' from author where last_name = 'Robuchon';