DROP TABLE IF EXISTS books, authors;

CREATE TABLE  books(
id INT AUTO_INCREMENT PRIMARY KEY,
author_id INT NOT NULL,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);

CREATE TABLE  authors(
author_id INT AUTO_INCREMENT PRIMARY KEY,
author_name VARCHAR(250) NOT NULL
);